package-lock.json, package.json, src/components/project-detail/ContributorsAvatars.tsx, src/components/project-detail/ProjectHeader.tsx, src/components/project-detail/ProjectSidebar.tsx, src/components/project-detail/VersionCard.tsx, src/components/project-detail/VersionList.tsx, src/pages/project/[projectId].tsx, src/types/project.ts
- 프로젝트 상세페이지 전반의 props 구조와 타입을 정리하고 UI를 개선했습니다.
- 실제 컴포넌트에 필요한 데이터만 전달되도록 최적화하고, 타입 재사용성을 높였습니다.
- VersionCard, VersionList UI 구조 및 스타일 개선
- ProjectDetailPage에서 Version 전체가 아닌 VersionSummary 타입으로 대체
- 중복 선언된 타입 제거 및 types/project.ts에 정의된 타입으로 일원화
- 시간 포맷 기능을 위한 date-fns 라이브러리 추가
- TailwindCSS 기반 스타일로 전체 컴포넌트 통일
resolved #21
=> refactor: 프로젝트 상세페이지 컴포넌트 및 UI 구조 개선

.github/workflows/semgrep.yml
- 사용자가 등록한 레포지토리의 특정 브랜치를 대상으로 Semgrep을 활용한 정적 분석 자동화를 수행하는 Github Actions 워크플로우를 추가했습니다.
resolved #32
=> feat: Semgrep 정적 분석 워크플로우 추가

src/components/Footer.module.css, src/components/Footer.tsx, src/components/Header.module.css, src/components/Header.tsx
- src/components 경로에 생성
- Header.tsx
- Header.module.css
- Footer.tsx
- Footer.module.css
resolved #34
=> feat:Header 및 Footer 컴포넌트 추가

src/pages/code-analysis.tsx, src/pages/deployment-approval.tsx, src/pages/docker-analysis.tsx, src/pages/image-analysis.tsx
docker-analysis-page 정적인 요소 삭제
- docker-analysis-page 정적인 요소 삭제
- code-analysis 승인 또는 취소 버튼 삭제 -> Next 버튼으로 다음 페이지 갈 수 있게만 추가
- image-analysis 승인 또는 취소 버튼 삭제 -> Next 버튼으로 다음 페이지 갈 수 있게만 추가
- deployment-approval 코멘트 기능 삭제
=> docker-analysis-page 수정

.github/workflows/semgrep.yml
semgrep sarif 파일 확인을 위해 디버깅을 추가합니다.
changes
resolved #38
=> chore: sarif 파일 디버깅 추가

.github/workflows/semgrep.yml
- semgrep sarif 파일에서 불필요한 메타데이터 제거합니다.
- semgrep 분석 결과 sarif 파일에서 불필요한 메타데이터 제거합니다.
resolved #43
=> refactor: semgrep 결과 sarif 파일에서 불필요한 메타데이터 제거

.github/workflows/build.yml, dockerfile, entrypoint.sh
=> feat: rds 추가

.github/workflows/build.yml, package-lock.json, src/pages/deployment-approval.tsx, src/pages/index.tsx, src/pages/project/[projectId]/version/[versionId]/code-analysis/[issueId].tsx
deploy 단계의 docker run 명령어를 여러 줄(\ 사용)에서 한 줄로 수정하여,
줄바꿈 파싱 문제로 인한 컨테이너 실행 오류를 수정
docker run -d --name my-container -p 3000:3000 -e DATABASE_URL=${{ secrets.DATABASE_URL }} ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest 한줄로 수정
=> fix: 줄바꿈 파싱 문제로 인한 컨테이너 실행 오류를 수정

prisma/schema.prisma
refactor: schema더미파일 test
ci/cd 마이그레이션이 정상적으로 작동하는지 schema 테스트
prisma/schema.prisma 에서 test 모델 생성
없음
=> refactor: schema더미파일 test

.gitignore, src/services/db-access-service/user.db.service.ts
User 모델에 대한 데이터 접근 계층(DAL)을 구현하여, 사용자 정보와 관련된 CRUD 및 조회 기능을 제공하는 `UserDBService`를 추가했습니다.
- `src/db-access/user.db.service.ts`: 다음 함수들을 포함하는 사용자 DB 서비스 모듈 신규 생성:
- `findUserById`: ID로 사용자 조회
- `findUserByEmail`: 이메일로 사용자 조회
- 각 함수는 Prisma를 사용하여 PostgreSQL 데이터베이스와 상호작용하며, 기본적인 오류 처리를 포함합니다.
#58
=> feat:사용자 데이터 액세스를 위한 UserDBS 서비스 구현

src/pages/dashboard.tsx
필요없는 폴더 삭제 및 대시보드 라우터 이름 변경
- pull 잘못 받아서 생긴 Intellisia 폴더 삭제
- dashboard.tsx에서 페이지 클릭시 이동하는 url 변경
fix #69
=> fix : 필요없는 폴더 삭제 및 대시보드 라우터 이름 변경

package-lock.json, prisma/migrations/20250521104522_add_test_model/migration.sql, prisma/migrations/20250521104935_remove_add_model/migration.sql
refactor: schema더미파일 test2
ci/cd 마이그레이션이 정상적으로 작동하는지 schema 테스트
prisma/schema.prisma 에서 test 모델 생성
x
=> refactor: schema더미파일 test2

prisma/schema.prisma
refactor: schema더미파일 test3
ci/cd 마이그레이션이 정상적으로 작동하는지 schema 테스트
prisma/schema.prisma 에서 sunwoo모델 생성
x
=> refactor: schema더미파일 test3

prisma/schema.prisma
refactor: schema더미파일 test3
ci/cd 마이그레이션이 정상적으로 작동하는지 schema 테스트
prisma/schema.prisma 에서 sunwoo모델 생성
X
=> refactor: schema더미파일 test4

package.json, prisma/migrations/20250521145706_date/migration.sql
- migration 파일 자동 생성 스크립트를 추가했습니다.
- 로컬에서 schema.prisma를 수정한 뒤 npm run migrate를 입력하면
자동으로 migration 파일이 생성되고, 이를 git에 커밋하면 RDS에 반영됩니다.
changes
resolved #79
=> chore: migration 파일 자동 생성 스크립트 추가

src/components/Header.tsx
헤더 로고에 대시보드 이동 기능 추가
-src/components/Header.tsx에 인텔리시아 로고 누르면 대시보드로 이동 
#87
=> feat : 헤더 로고에 대시보드 이동 기능 추가

.github/workflows/build.yml
ec2에 env 파일 주입되도록 추가합니다.
=> docker run 시에 --env-file .env 명령어로, env 파일의 내용이 컨테이너의 환경변수로 주입됩니다.
resolved #53
=> chore: ec2에 env 파일 주입되도록 추가

src/pages/project/[projectId]/prepare-run.tsx
배포 준비 페이지의 프론트엔드의 기능적인 측면을 제외하고 목업을 구현하였습니다.
changes
#99
=> feat:배포 준비 페이지 프론트엔드 목업 구현

src/components/project-detail/VersionList.tsx
- 로컬에서 npm run dev로만 테스트하여 발생한 빌드 누락 문제 수정
changes
=> fix: VersionCard 타입 요구에 맞춰 id prop 전달

prisma/migrations/20250524112838_s3_url_add/migration.sql, prisma/schema.prisma
프리즈마 마이그레이션
+ versiontable에  imageAnalysisS3Url String? 추가 했음
=> chore : 데이터 스키마 변경

.github/workflows/image_build.yml
사용자에게서 callbackUrl과 projectId를 입력받지 않고, callbackUrl은 코드 안에서 지정해 줌 
callbackUrl과 projectId 삭제
callbackUrl은 코드 안에서 지정해 줌
=> fix: callback_url, project id 삭제 

.github/workflows/image_build.yml
ECR 대신 도커 허브에 이미지를 올리도록 image_build.yml 파일을 변경
changes
resolved #128
=> chore: ECR 대신 도커 허브에 이미지를 올리도록 image_build.yml 파일을 변경

src/pages/create-project.tsx
create-project.tsx 파일 내에서 프로젝트 생성 시 발생하던 특정 오류를 해결했습니다.
create-project (프로젝트 생성 요청) 버튼을 누르면 -> https://intellisia.site/project/test (프로젝트 상세 페이지)로 이동하는 방향성으로 수정하기도 했습니다.
create-project.tsx 파일 내에서 프로젝트 생성 시 발생하던 특정 오류를 해결했습니다.
=> fix:프로젝트 생성 로직 개선 및 오류 수정

src/services/version-service/version-generator.service.ts
프로젝트 내 최신 버전명을 기준으로 다음 버전 이름을 자동 생성합니다.  
생성 시 중복(P2002) 발생 시에는 0.5씩 증가하며 최대 5회까지 재시도합니다.
changes
resolved #135
=> feat: 자동 버전 네이밍을 위한 최신 버전 조회 및 중복 시 대응 로직 추가

src/components/version/DeployButton.tsx, src/pages/project/[projectName]/version/[versionId]/index.tsx, src/services/deployment-service/trigger-deployment-workflow.ts
- DeployButton 컴포넌트: 배포 상태별 동적 UI 및 에러 처리
- 배포 API 3개: 배포 실행, 승인 결정, 배포 결과 콜백
- GitHub Actions: argocd-apps 레포 업데이트 워크플로우
- 플로우 페이지: 승인/배포 버튼 통합 및 실시간 상태 업데이트
index.tsx 변경 사항 
- DeployButton 컴포넌트 추가
- fetchStatus 함수 스코프 수정
- 배포 완료 콜백 핸들러 추가
- 배포 단계에 버튼 렌더링
#158
=> feat:배포 실행 버튼 & 플로우 페이지 구현

.github/workflows/image_build_and_scan.yml
image_build_and_scan.yml 파일의 경로 지정 문제 해결.
=> fix : 이미지 빌드 및 스캔 워크플로우 경로 지정 문제 해결

.github/workflows/image_build_and_scan.yml
http 요청을 - https로 바꾸고, 인증서를 무시하는 -L -K 추가했어요
=> fix : 빌드 워크플로우 경로 수정

src/pages/project/[projectName]/version/[versionId]/deployment-executed/index.tsx
배포 페이지 버튼 눌렀을 때 argoCD로 가는 기능 활성화
src\pages\project\[projectName]\version\[versionId]\deployment-executed.tsx 추가
resolved #174
=> feature : 배포 페이지 버튼 활성화

src/components/Header.module.css, src/components/Header.tsx, src/pages/create-project.tsx, src/pages/dashboard.tsx, src/styles/Dashboard.module.css
fix: UI 변경
- Header.tsx 에서 오른쪽 프로필 제거
- create-project.tsx 에서 footer 제거
- dashboard.tsx 에서 버튼 이름 영문으로 변경
fix #178
=> fix: UI 변경
